# Generated by Django 5.1.1 on 2024-10-11 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_defuncion', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='artistas')),
                ('biografia', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tecnica', models.CharField(max_length=100)),
                ('dimensiones', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='obras')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Artista.artista')),
            ],
        ),
        migrations.CreateModel(
            name='Exposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('obras', models.ManyToManyField(to='App_Artista.obra')),
            ],
        ),
    ]
