# Generated by Django 5.1.1 on 2024-10-11 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Artista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista_invitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('texto_motivacional', models.TextField()),
                ('link_obras', models.URLField()),
                ('exposicion_anfitriona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Artista.exposicion')),
            ],
        ),
    ]
