# Generated by Django 5.1.1 on 2024-10-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Artista', '0002_artista_invitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista_invitado',
            name='Email_contacto',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
